### ISSUE TITLE
Theme --> design value edits does not save when published

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1765]
Theme --> design value edits does not save when published

**Comment by lordofnos** [comment]
i have the same issue... sometimes it works when clearing cache after saving. but it does not work every time.

**Comment by neil96** [comment]
Hi @prepperz and @Scheinwelt-Media 

This is a browser cache issue. When you edit the values and click to **publish**,  the file /PF.Site/flavors/{theme_name}/assets/autoload.css (url http://yoursite.com//PF.Site/flavors/{theme_name}/assets/autoload.css) is updated. But your cache browser cached it (because the url does not change).

This issue only happen with **Admin user** only. If you get it, please close your browser then re-open it again or clear your browser cache.

Regards.
