### ISSUE TITLE
Can't install younetco themes

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1900]
Hi guys, anyone encounter an issue just like this? When i tried to install younetco themes. . It display a message "Provide a name for your theme." The page goes blank and some component in the homepage appear also. How to fix this issue or is there any other way just like importing of new themes, i can't find where to import an existing themes.
![image](https://cloud.githubusercontent.com/assets/16043743/23886117/3c8999ba-08b3-11e7-8e37-cc5ebf2a31b0.png)

Thanks

**Comment by PhpFoxJohnJr** [comment]
Yes and I contacted phpfox and they of course reminded me that my support has run out and they do not handle third party issues. Getting tired of doing their job for them...may give up on project beca use every they touch the code we get more bugs.

**Comment by sanjosedennis7593** [comment]
Yes i turned on techie mode, it's now okay but the issue still the same, what i did is some sort of hack. I just copy the theme to PF.Site directory, then copy some files from PF.Base modules, then it works.

**Comment by PhpFoxJohnJr** [comment]
I installed it from the store.  I did the same type of hack...went back to previous backup and got the files.  My install said missing json files.

**Comment by neil96** [comment]
Hi @sanjosedennis7593  and @PhpFoxJohnJr ,

I can't reproduce your issue. But below things can help you:
- phpFox 4.5.1b2 and older do not support re-install a theme (supported from 4.5.2). If you'd like re-install, kindly remove the folder of theme in PF.Site/flavor.
- If the package that you'd like to install larger than 2MB, please increase the configuration `upload_max_filesize` on your server.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Neil,
I have not attempted to reinstall from scratch lately because I gave up on 4.5.1b2.  But if I get some time tomorrow I will try again.

A few things you should know though...
My error every time (as I tried it a few time) was the same image as above except mine said missing json file.  I check the folders and they were all there.  I did not go though each file though.

I did a fresh install each time.  Their was no add-on as the theme was my first thing I attempted to install.  Well it was not at first as it was like 20 but after it goofed up the first time I decided to see if I could get that fixed before installing anything else.

my upload_max_filesize is 8m which is what it has always been.  I do a lot of hacking so I have done fresh install probably hundred times over the past 6 months and this theme has never given me any issue on installing.

Like I kinda of mention before I just and got a back up and through the folders in and then it worked.  So that tells me it does load any database stuff if there is any...I can't remember.  Good night...gotta get up in 5 hours.

**Comment by PhpFoxJohnJr** [comment]
Oh yeah...I am using php 7.something which I know is goofing up your texteditor so maybe that is messing up the install ?

**Comment by neil96** [comment]
Thanks @PhpFoxJohnJr, I will test again with new information that you gave.

**Comment by neil96** [comment]
Hi all,

We have some improvements relate to this issue. Please help us re-test this issue after 4.5.2 is released. Thanks!

Regards.

**Comment by PhpFoxJohnJr** [comment]
Ok guys...installed new version and only installed this theme from the store and I get the same thing as listed above so I guess it is not working...in case you can't see the first image it says provide a name for your theme.

**Comment by PhpFoxJohnJr** [comment]
I contacted YouNet (the other version of you guys) and of course this is what they always want.

Dear my name,

Please send us your site details so we can make a quick check.
We need
- Site URL
- Admin account
- Ftp account

Best Regards,
Vu Do
Customer Support Team
For latest news and tips on how to make your social network a success, follow us on:
Facebook: https://www.facebook.com/YouNetCo


Now if two people are having the same issue on new installs before I give out anything I would have like to see that they at least tried it out on their own before getting into my stuff.

**Comment by PhpFoxJohnJr** [comment]
This is for the clean theme.

**Comment by robert9592** [comment]
can reproduce now with php version 7.1.x
