### ISSUE TITLE
Removing unused phrases

### ISSUE THREAD

**Issue by b-jerome** [PHPfox-Official/phpfox-v4-issues#2039]
It seems that phrases are not removed when i uninstall an APP.

Looking at the language_phrase table, module_id is always NULL and product_id is always "phpfox" so that is not easy to delete unused phrase.

**Comment by neil96** [comment]
Hi @b-jerome ,

Phrases are common in all apps and core. By default, we do not remove the phrases of the app at uninstall. However, we have support for the 3rd-party app remove phrases at uninstall.

In the table `language_phrase`, the two fields `module_id` and `product_id` are no longer used from version 4.5.0. We also keep them because many app queries on these two fields. Removing abruptly from phpFox will cause many apps to crash.

Regards.

**Comment by b-jerome** [comment]
That make sense for the core APPS of course but phrases from 3rd-party APPS aren't removed. I created some own APPS and tried a few 3rd-party APPS from phpfox store and phrases are not removed.

**Comment by neil96** [comment]
Hi @b-jerome ,

Due to the phrases are shared, removing the phrase when uninstalling the app causes other apps to be missing the phrase.
This mechanism will save you a lot of time to translate the phrases, as many of the phrases between the app are completely identical. Having a few extra phrases will not affect performance on your site.
Regards.

**Comment by b-jerome** [comment]
Yeah ou are right that's not going to really impact the website. I just love when everything is "clean". I don't think that a phrase from 3rd party App with specific variable are really going to be used in other part but well...

I just noticed that 3rd party tables aren't removed neither ? That's a little bit more annoying when you have unused big tables.  

(sorry i have some difficulty to explain in english sometimes ;) ).

**Comment by neil96** [comment]
Hi @b-jerome ,

I understand your point. Developers can define the list of phrases will be removed when uninstall, but they do not define this. We will encourage developer do this.

Regards.
