### ISSUE TITLE
Option to "Sponsor in Feed" for photos missing?

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2188]
## Steps to reproduce:
1. Login as admin
2. Click on photo in main menu
3. Click on gear on a photo, option to Sponsor in Feed is not there?

## What is expected
Should be able to sponsor photo in feed

## Browsers tested
Firefox

## Server informations
...

## phpFox versions
phpFox 4.6.0, Photo app 4.6.1

## Screenshots

Option to Sponsor in Feed missing in Photos
![sponsor-in-feed1](https://user-images.githubusercontent.com/17064302/36687613-0ba691e0-1b22-11e8-90a9-bec584360c8d.jpg)

Option to Sponsor in Feed present in Videos
![sponsor-in-feed2](https://user-images.githubusercontent.com/17064302/36687614-0bc1a5e8-1b22-11e8-9af6-4f3aec626a34.jpg)

It seem that only videos can be Sponsored in Feed?

**Comment by neil96** [comment]
<img width="284" alt="screen shot 2018-02-27 at 07 50 09" src="https://user-images.githubusercontent.com/15936115/36704509-3e5a2888-1b93-11e8-9f7b-2a892c6583d4.png">

Could you double check your ads/sponsor configurations.

Regards.

**Comment by starplan** [comment]
Thanks for your response Neil.

"Sponsor in Feed" was there prior to upgrading to photo 4.6.1 as I was testing the feature. I haven't altered any settings since the upgrade. These are my Administrators Photo app settings.

![sponsor-in-feed3](https://user-images.githubusercontent.com/17064302/36706793-71e259f8-1b63-11e8-83f3-b1efb360e168.jpg)

Can't figure what has changed here.

Regards

**Comment by spirogg** [comment]
@neil96 
@starplan 
the problem I just check is the photo needs to be added in feed in order to sponsor in feed.

![capture1](https://user-images.githubusercontent.com/17736688/38845422-faab7c9a-41bc-11e8-920c-b3b911c59b78.PNG)

![capture2](https://user-images.githubusercontent.com/17736688/38845424-fe38add8-41bc-11e8-9c9f-36882d731ebc.PNG)


 if the photo was added to photos it does not seems to have option to sponsor in feed 

![capture](https://user-images.githubusercontent.com/17736688/38845430-03529644-41bd-11e8-8b9a-83053f112344.PNG)


1) i add a photo from photo app then i tried to sponsor in feed, but not have that option
2) I go to feed and add a photo then click on photo and I can sponsor in feed 

is this a bug ?

**Comment by spirogg** [comment]
@neil96 Also I notice you have to clear cache every-time in order for sponsor photo in feed to show up in feed ?
is there a way to have this feed update right away with sponsor in Feed without clear cache? because users wont have option to clear cache ??
