### ISSUE TITLE
Language and lost phrases

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2242]
## What happened?
When updating to 4.6.1 (in my case from 4.5.3b3) most of the language phrases for custom language are gone. I have to update all phrases by hand. Importing a language file shows 500 error.

## Steps to reproduce:
Update to 4.6.1 with second language installed.

## What is expected?
Language phrases should stay. New phrases should be added.

## Browsers and Devices tested
All browsers

## Server information
Linux, PHP5.6.35, Appache

## phpFox version
4.6.1

## Screenshots
![phrases](https://user-images.githubusercontent.com/13225682/38781836-6a469daa-40eb-11e8-80ad-0fbf8cc6037b.png)

**Comment by neil96** [comment]
In phpFox 4.6.1, we restrict phrase var_name format, it only allows lower case and underscore (_) character. Because many 3rd parties use whitespaces or special characters for var_name. When exporting to xml file, many special characters are not accepted so it can not be imported again. This rule has been available from phpFox v3. If it affects too much to your applications. You can request that we update this rule.

Regards.

**Comment by Scheinwelt-Media** [comment]
the issue happens with core apps... that is the problem. we have to translate all core app phrases again after updateing to 4.6.1. third party apps are fine... at least my own. i dont know if other third party apps have issues.

**Comment by neil96** [comment]
Thanks! I will double check this.

**Comment by Scheinwelt-Media** [comment]
thanks neil

**Comment by Scheinwelt-Media** [comment]
to reproduce this set another language than english as default and update. maybe the issue only occurs when updating from 4.5.3b3... i dont know.
