### ISSUE TITLE
Looks like a scam bullcrap coders!

### ISSUE THREAD

**Issue by VlogMe** [PHPfox-Official/phpfox-v4-issues#2373]
You guys can not even spell properly, or use grammar properly, what a shod mess you guys are! Shame.

**Comment by spirogg** [comment]
@VlogMe whats your issue are you a spammer, scammer, full of bullcrap or do you have a legit complaint ? if not go complain elsewhere..

**Comment by spirogg** [comment]
@neil96 @harrison05 @paulkellow remove - block this idiot

**Comment by VlogMe** [comment]
Screw you, scammers, look https://www.phpfox.com/ That's all lies and bullshit. Remove me? I will have you pulled from Github fucken scammers

**Comment by Elshara** [comment]
Just because the script changed hands from a U.S. based company to
some other country, DOESN'T give you the right to say it's a product
without merit.
I really don't care if the person now developing PHPFox is name is Kim
Jung Un, At least it's getting developed with modern features and bug
fixes people need.
Git Hub is for serious developers to talk about what has to be worked
on. Not some place where people who haven't given it a chance to
complain.
I can tell you where a legit use of broken English has occurred in
this script. Yes.
I can inform you where a legit use of broken English can be fixed with
the help of a network creator or administrator. Yes.
Do I think the script is bad? Absolutely not! It's one of the the most
modern, safe and compatible scripts to use out there on websites
today. There are certain features of it that don't necessarily work as
advertised, yes. But that doesn't mean that it's a complete dud or
waste of time.
Please take your comments elsewhere. If you bought a license, or are
trying a demo, and have found that you are getting a lot of bots
entering your site, know this. It isn't just you. It isn't just a
problem with PHPFox. It's not up you as a guest to control the
direction of those who use this script for their business needs. If
PHPFox didn't allow people to help make it better in such an open
environment as Git Hub, we would be well worse off for where, I
guarantee you that. Please reconsider this. I am not getting paid to
write this. I am a real user, I have a real site, I am a supporter of
the platform for what it is able to do well.
Furthermore, I'm sorry you've had a bad experience with PHPFox. Please
don't blame those who are trying to put in effort to change this for
the better, as it isn't our fault. Git Hub isn't the place to discuss
whose fault it is, unless you can prove that this actually happened.
As you haven't shown us that, I'm kindly asking you to refrain from
saying it's all bad. PHPFox I know is a work in progress.
Thanks.
