### ISSUE TITLE
Attachments are shrinked while adding through description

### ISSUE THREAD

**Issue by chena321** [PHPfox-Official/phpfox-v4-issues#2389]
When uploading images through attachment under description, the images are getting resized. 

I'm using Younet products and have issues with them.  When I reported it, they said its on everywhere even on core apps since the issue is from attachment app.  Then I tested on phpfox demo and the issue there too. 

...

## Steps to reproduce:
1.  create a blog and attach an big image
2.  check the blog and see the size of the attached image

## What is expected?
should not resize the image 

Its does on Edge, firefox.  Windows 10.  

tested on v4.phpfox.com  too.

## Server information
 CentOS 7, php 7.1 apache)

## phpFox version
 phpFox 4.6.1b5)

**Comment by spirogg** [comment]
@chena321 @harrison05 

you adjust it here for attachments ? in Apps >Attachment > Settings

Thumbnail Width/Height
120

Define the width and height of the thumbnail that will be created after a user uploads an image. If the image uploaded is smaller then the specified width/height it will not create a thumbnail for the image.

Medium Thumbnail Width/Height
600

Define the width and height of the medium thumbnail that will be created after a user uploads an image. If the image uploaded is smaller then the specified width/height it will not create a medium thumbnail for the image. 

Note that the medium thumbnail is displayed on the website instead of the original image to save bandwidth.
read here it has photo the medium Thumbnail you can increase to increase blog photos

https://community.phpfox.com/forum/thread/57448/image-compression/view_350323

**Comment by spirogg** [comment]
here is a demo of mine 3 photos in blog, medium was set to:
1200 for one 
600 for the other 
and 480 for the last one, 

so you can see if you set the Medium Thumbnail so you can achieve the size you want :)

just experiment

Medium Thumbnail Width/Height
1600 or 1200 or 800 or 600 or 400 etc..

Define the width and height of the medium thumbnail that will be created after a user uploads an image. If the image uploaded is smaller then the specified width/height it will not create a medium thumbnail for the image.

Note that the medium thumbnail is displayed on the website instead of the original image to save bandwidth

https://community.phpfox.com/forum/thread/57448/image-compression/view_350325

**Comment by harrison05** [comment]
Hi, we crop images when users attache to save site bandwidth and make it load faster when view item detail. But you can change crop size on it via setting: 
   **"Medium Thumbnail Width/Height"** (Define the width and height of the medium thumbnail that will be created after a user uploads an image. If the image uploaded is smaller then the specified width/height it will not create a medium thumbnail for the image. ) 

   You can found this setting at: **AdminCP > Apps > Attachment > Settings**, default setting is 600, it mean: If your image have width > 600, it will be crop. You can change it to any size you want.

Regards.

**Comment by harrison05** [comment]
@spirogg Yes, absolutely right!

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/45132993-aea3aa00-b158-11e8-96b6-b3917139575f.JPG)
