### ISSUE TITLE
Select Categories

### ISSUE THREAD

**Issue by kaligula7** [PHPfox-Official/phpfox-v4-issues#2394]
# Important!

Please follow this template!

----------------------------------------

## What happened?
I can select all categories by sharing

## Steps to reproduce:
1. Share an Blog (Video, Photo, ....)
2. Select all Categories (Control or Shift + right mouse button)
3. OK...

## What is expected?
I think that it is not a good idea to give the user the opportunity to select all categories in modules, when sharing elements.
For example - if I upload a photo, a blog, or a video and so on, then I can select all categories for the photo, blog, video (Control or Shift + right mouse button)

## Browsers and Devices tested
PhpFox-demosite:
https://v4.phpfox.com/blog/2367/select-categories/
https://v4.phpfox.com/photo/16365/marken_bmw_i_bmw_i8_freisteller/
https://v4.phpfox.com/video/play/828/create-a-social-network-website-with-phpfox/

## Server information
(Example: )

...CentOS 7, php 7.1 apache

## phpFox version
(0)

phpFox 4.6.1B6

![blogkategory](https://user-images.githubusercontent.com/21354832/45188053-32ca6000-b233-11e8-82c2-8eb687511b4d.JPG)
![photokategory](https://user-images.githubusercontent.com/21354832/45188054-32ca6000-b233-11e8-8ad5-f3bc723f5c2d.JPG)
![videokategory](https://user-images.githubusercontent.com/21354832/45188055-32ca6000-b233-11e8-8273-748be37baea2.JPG)

## Screenshots
...

**Comment by spirogg** [comment]
Good catch @kaligula7 
Maybe we should have a setting to control how many categories a user can select. To share - post - upload ? 
For each app. 

1- 2- 3 -4  etc. 

Also how many videos blogs pages groups music etc a user group can create or upload. 

So if we create user groups we can set limits. Also when creating subscriptions.
 Free - we can limit to less amount since they are free 
Med - they pay (example) 2.99 per month.  We give them a little more 
Pro - they pay (example) 9.99 per month and we give them alot to create of each app. So each app should have limits and category limits. 


I Agree with @kaligula7 this should be fixed.

**Comment by spirogg** [comment]
> (this will save us big headache if we get a few spammers that figure this out and slam our site and we as admins will have headache for days trying to clean the site)

**Comment by harrison05** [comment]
@kaligula7 Seem it has no issue here? Because those Apps working as our design. 
In case you have a request, you can add a topic to https://github.com/PHPfox-Official/phpfox-v4-feature-requests and we will review it.

Regards.

**Comment by spirogg** [comment]
@kaligula7 I make request for this

https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/722
