### ISSUE TITLE
Unauthorized users can edit other users' statuses.

### ISSUE THREAD

**Issue by alexram1313** [PHPfox-Official/phpfox-v4-issues#2406]
## What happened?
Users whose user group does not have permission to edit all statuses can still edit all statuses via a manual /_ajax/ call.

## Steps to reproduce:
1. Ensure that "Can edit all user status?" is disabled on the user group settings for "Feed" and that a user is logged in.
2. Retrieve the feed id for a status by another user via the page source under `. _app_user_status`.
3. Make the call the edit the status.
```
/_ajax/?core[ajax]=true&core[call]=user.updateStatus&val[feed_id]=FEED_ID_HERE&val[user_status]=TEXT HERE&val[status_info]=Hi!&val[privacy]=0&val[location][latlng]=&val[location][name]=&core[security_token]=TOKEN&core[is_admincp]=0&core[is_user_profile]=0&core[profile_user_id]=0
```
4. The edit should be reflected on the site.

## What is expected?
The edit should not be authorized and that status should remain the same.

## Browsers and Devices tested
Chrome, Vivaldi on macOS High Sierra and Windows 10

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
phpFox 4.6.1 b5/b6

## Screenshots
![user group setting](https://user-images.githubusercontent.com/9940538/45922144-00e30b80-be79-11e8-90b7-2b99dc518d82.png)

Original:
![Original](https://user-images.githubusercontent.com/9940538/45922150-312aaa00-be79-11e8-85c8-f154681b4071.png)

Call:
![Call](https://user-images.githubusercontent.com/9940538/45922157-561f1d00-be79-11e8-828f-ca5012529b71.png)

After:
![image](https://user-images.githubusercontent.com/9940538/45922162-72bb5500-be79-11e8-989b-b267c6ea7440.png)

Also tested on the demo site

**Comment by spirogg** [comment]
@harrison05 @alexram1313 

I'm wondering if this can Exploit Admins access, if you can make a _ajax/ call to change to admin phpfox, wonder if this can exploit an administrators access or make a user an admin ??

@harrison05 @paulkellow @Vivian-phpFox @davidnguyen88 

can you please check this since you guys kn0w the code so well :)

**Comment by spirogg** [comment]
@harrison05 
 maybe Srny, is having email spam to all users because of similar to this?

he has said in his original first post, he is getting spam to all user emails making it seem as its coming from his website ??

Please check link below in the community an advise - Please

https://community.phpfox.com/forum/thread/57438/spam-emails-sent-using-our-site-mail-configuration-and-credentials/
