### ISSUE TITLE
Advertise app menu does not appear in main menu

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2440]
Advertise app (ad) menu does not appear in main menu. The one at the in the footer (ad.manager) is displayed. Is this supposed to be one app or two?

**Comment by harrison05** [comment]
They are one app. Currently, phpFox always hide menu with URL "ad" in main menu, we will update this case later. Btw, if you want to show Advertise in main menu you can change this URL to "ad/manage" in **AdminCP > Appearance > Menus**.
Note: By default, with the newest version of Ad App, it don't add this menu to main menu, so your site has this menu without manual add might because it was upgraded from an older version.

**Comment by harrison05** [comment]
Fixed in 4.7.2. Please check.
