### ISSUE TITLE
Cannot access installed apps if  App store is down or unavailable

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2555]
## What happened?
Cannot access installed apps

## Steps to reproduce:
1. goto installed apps section when store is not available
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/51293694-fc210500-19dd-11e9-8cc2-18459ecb396f.png)

**Comment by kerstar** [comment]
Hi,
This may be a problem, because what will happen if you change the port address for the store after some time and the user will use the old version of the script? 
Do not get access to my applications?
Harrsison can you fix this issue on my site? 
The access data to the website was given in the ticket number #790399
Thank you.

P.S.
Yes, I know you will probably fix it in 4.7.3, but I will not be able to update the script to this version, so I want this bug to be fixed. I hope you understand me and help me fix this issue on my site. Thank you.

**Comment by harrison05** [comment]
@prepperz Could you check again? Because our Store is still working well.
@kerstar Please follow your topic, I just replied it.

Regards.

**Comment by kerstar** [comment]
@harrison05 I checked and gave you the answer in my topic.

**Comment by prepperz** [comment]
@harrison05 Yes, it works well when the store works. I just wanted to point out that if the store is not available, site admins will not be able to access the installed apps to make any changes they need to properly operate the site. They should be able to access the installed apps regardless of whether it is connected to the store or not.

**Comment by kerstar** [comment]
@prepperz  is right. This may cause difficulties and large complications if you change the address of the store or for other reasons you will not be able to connect to the store for a longer period of time.

**Comment by kerstar** [comment]
@david-phpFox 
Hi. David, is it possible for you to fix this issue on my site? On Monday I would like to give the script to the programmers so that they can start working on modifications to the script. In the future, I will have big problems with updating phpfox to a newer version. That is why it is important for me that important errors be repaired before I pass the script to the developers. I do not want to wait another month for the release of phpfox 4.7.3...
P.S. Waiting more than a year until phpfox will be stable enough to start working on the introduction of modifications ... Phpfox I bought in December 2017 and I was waiting for the pride to have phpfox stable enough to start work... You can ask Paul that I wait a long time. I hope you will understand me. Thank you.

**Comment by kerstar** [comment]
Guys?

**Comment by harrison05** [comment]
You should submit a ticket to us if you want a hotfix on your site because we will fix on 4.7.3.
Btw, our Store is working well now and the issue doesn't appear anymore, I don't think you really need to fix it immediately and you can wait for the next release.

Regards.

**Comment by kerstar** [comment]
I understand. I've been waiting a year and I can wait another month. Thanks ;(
