### ISSUE TITLE
No space break is adding a space in CKeditor

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2562]
## What happened?
No space break is adding a space

## Steps to reproduce:
1. Goto pages info and edit. Type something in.
2. Hit Shift + Enter
3. Type in something and save

## What is expected?
It will look fine from within ckeditor, but the info page front end does not reflect it. It should not have a space in the line break, but it does when it is rendered.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Could you explain more about your issue? I think it's working correctly.
![screen shot 2019-01-23 at 09 43 43](https://user-images.githubusercontent.com/41947198/51579403-69a7c680-1ef3-11e9-9210-bf5a9d3235f3.png)

**Comment by prepperz** [comment]
It will look fine in the editor. Go look on the info page front end

**Comment by harrison05** [comment]
![screen shot 2019-01-24 at 09 43 50](https://user-images.githubusercontent.com/41947198/51650903-9673e080-1fbc-11e9-8518-cf277457828e.png)
Ok, It seems space between 2 lines when showing is too big because **Parse Output** library in Core processed it. This library might be working incorrectly with CKEditor, we will check this case.

Regards.
