### ISSUE TITLE
BLOCKS

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2616]
Hello,
Wanted to know when we create a block with Html or Php
Where the file of the block created is stocked on the server ?
I want to create a block and customize it with html css and JS
Also the compenents of the block like register block in Index core guest user
Where the code is ?

**Comment by harrison05** [comment]
The source code of Block with type _HTML code/PHP code_ is saved at table **<prefix>_block_source**

Regards.

**Comment by AmineBAIK1** [comment]
Okey the source code of Blocks created are stocked at table _block_source
But the question is.. Where do core blocks content source code are stocked..
like the Register if i want a customize register with my own html and js.. 
![ScreenRegister](https://user-images.githubusercontent.com/46829598/55549270-bff46b00-56d5-11e9-9aae-5b9277e044ea.png)

**Comment by harrison05** [comment]
Okay, this component belongs to module User, you can find the source code at:
```php
PF.Base/module/user/include/component/block/register.class.php
```
Btw, if you want to customize other blocks, see my screenshot
![Screen Shot 2019-04-05 at 09 35 28](https://user-images.githubusercontent.com/41947198/55600577-cdb5f900-5786-11e9-97bb-7c9bcbdc5f6c.png)
Based on module id, you can found the relative path of that module, example: **PF.Base/module/user** and all blocks source is storage at **PF.Base/module/user/include/component/block**, and based on block component id you can found it.

But if you can't find this module at **PF.Base/module**, you should find it at **PF.Site/Apps/<apps_dir>/Block** (because it is an app, not a module, to find apps_dir you can search in table **phpfox_apps** with app_alias = module id)

**Comment by AmineBAIK1** [comment]
Thanks for this clear and elaborate answer.
Regards.
