### ISSUE TITLE
mCustomScrollBox

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2622]
Hello,
I am trying to modify my registerblock and i have a quick question.. 
I cant find those css files (mCustomScrollBox mCSB_container....) 
Where do i can get them
![Capture d’écran de 2019-04-16 13-57-55](https://user-images.githubusercontent.com/46829598/56208074-8e25c180-6050-11e9-968e-214667cd8f33.png)

**Comment by harrison05** [comment]
Ohh, phpFox doesn't control that CSS file. Because of mCustomScrollBar is a jQuery library, and it controls class name and CSS by itself, the relative path is **PF.Base/theme/frontend/default/style/default/css/jquery.mCustomScrollbar.min.css**

But, if you only want to modify CSS at RegisterBlock, you should write CSS in your file, don't change library CSS file because it might affect other places.
