### ISSUE TITLE
JAVASCRIPT POPUP

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2666]
Hello,
I have a problem with popups!
I put a Javascript in Jquery When i click on [LookScreens] The community for exemple i wanted to get the {content} in fullscreen i change css of some sections/divs and it's working proprly.
I have my item in fullscreen like a want.
BUT when i open the Login popup then i close it. Then i click on the community the jsbutton it's not working anymore. What can causes that in the Popup?
![Capture d’écran de 2019-05-22 15-12-27](https://user-images.githubusercontent.com/46829598/58177866-6b1cac00-7ca5-11e9-9d91-d0728acaa731.jpg)
![Capture d’écran de 2019-05-22 15-12-27(1)](https://user-images.githubusercontent.com/46829598/58177874-6f48c980-7ca5-11e9-909c-315b20472f76.jpg)

**Comment by harrison05** [comment]
I think your button is unbound javascript event after Login popup show/close. 
Let try to add class "dont-unbind" to it or "dont-unbind-children" to its parent element.

Regards.

**Comment by AmineBAIK1** [comment]
Hi,
It's working but like for 2/3 secondes and becomes like it was...

**Comment by AmineBAIK1** [comment]
I just want to open this button in a new tab with![Capture d’écran de 2019-05-27 15-45-36](https://user-images.githubusercontent.com/46829598/58424027-cb8d5e00-8096-11e9-8829-c77b3f89234a.jpg)
that content ![Capture d’écran de 2019-05-27 15-47-05](https://user-images.githubusercontent.com/46829598/58424032-cd572180-8096-11e9-960b-8f96f5ea0c49.jpg)

**Comment by harrison05** [comment]
If you want to open a link in a new tab on phpFox, you have to add attribute **target="_blank"** and class **no_ajax** to <a> tag.

**Comment by AmineBAIK1** [comment]
I know how to open a link a new tab, I want to open the link in a new tab but only with Screen2 and not all the layout.

**Comment by AmineBAIK1** [comment]
I think your button is unbound javascript event after Login popup show/close. Let try to add class "dont-unbind" to it or "dont-unbind-children" to its parent element. Regards

--
And why this method works for 2secondes?

**Comment by AmineBAIK1** [comment]
@harrison05

**Comment by harrison05** [comment]
> I know how to open a link a new tab, I want to open the link in a new tab but only with Screen2 and not all the layout.

Currently, phpFox doesn't support you do this. If you want to display a view with a different layout you must:
- **Solution 1**: in your component controller, add this function in the last of function **process()**:
```php
Phpfox_Module::instance()->getControllerTemplate();
die;
```
But if you do this, the page of that controller only render HTML like view file (<view>.html.php) of it without core structure template (blank page with your content only and use smarty format) you must init css, js manually.

- **Solution 2**: you have to custom source of phpFox, create your **Screen2.html** file and placed inside current theme folder respectively to **layout.html**. Clone file **PF.Base/views/layout.html** with name **Screen2.html**, then add it to **PF.Base/views/**. The last step, call this function in your component controller (at process() function):
```php
$this->template()->setTemplateLayout('Screen2');
```

> And why this method works for 2secondes?

Because when JS on phpFox re-init (When some core js function is called, ex: $Core.loadInit()), it will bind event again into your element.

**Comment by AmineBAIK1** [comment]
Ok thanks a lot @harrison05 that help me a lot but where is 
 Component/ Controller .class file of Terms and Policy with the function process??

**Comment by harrison05** [comment]
Terms and Policy are Pages, not components. You can find it at **AdminCP > Appearance > Pages**.
