### ISSUE TITLE
Stripe payment 

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2675]
Is it possible to add Stripe Payment GateWay in Phpfox ?

**Comment by harrison05** [comment]
Currently, we don't have a plan to add Stripe to phpFox. 
Btw, you can check other 3rd Gateway apps on phpFox Store, they already supported it.

Regards.

**Comment by joblux** [comment]
I cant imagine even how Stripecould be ignored like being such a major actor  .... its insane....Sociel Engine has it for a while no wonder they are moving way forward phpfox ...so what it is exactly that you guys are workign on except fixing bugs that a brave small commuynity keep forwarding to you ? Whats your vision ?  Because most of plugsin a i see are unfinished and getting nowhere ..

**Comment by hamadax** [comment]
> most of plugsin a i see are unfinished and getting nowhere

I certainly agree with you. I bought a few apps and none was polished enough to be on a production site with too many bugs... some needed a complete rewrite of their language file. Something that PHPFox itself needs to desperately improve upon is the English language file, which is not production ready - too many mistakes as if it was written by a non-speaker or translated with a program.

The issue with the two major app developers in the store is when you report the bugs and the obvious elementary logic issues, they are so slow to fix the issues and tend to classify logic issues as paid enhancements. I think we are all fine with paying for rock solid apps!

**Comment by joblux** [comment]
Same here i cant launch any serious website with what they offer ... it looks great on the presentation with all the bells and whitles but when you dig it further ... its totally irational the whole logic of it all...have you tried Social Engine or Una ?

**Comment by tedkipling** [comment]
Hi AmineBAIK1 and all,
phpFox is a platform to build a social network (SN) or an online community. We have attempted to provide features so that you could mix them to build up your own SN easily instead of building from a crash.  It saves time and cost a lot. 
Though our team has worked hard, we could not provide all modules (apps) because the diversity of is very large. Please help to understand that.

Fortunately, we have accompanying 3rd parties providing apps at https://store.phpfox.com/ so that you have more options. You could search there to find suitable apps and mix the phpfox's apps and/or 3rd parties' to form your own SN solution. In case your idea is quite new, you could think of customization service to get a development team support or yourselves. 

Regarding Stripe Payment Gateway, phpFox does not provide it but there are options provided by 3rd parties, they also have the product description, demo and even you could contact them to get help.

**Comment by joblux** [comment]
Third partie have shown little reliability, sorry to say that but all we have are buggy module with shady support once the payment is made. Overall a whole disappointment to use phpfox as of today.
