### ISSUE TITLE
Cannot add certain video sources

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2699]
## What happened?
cannot add video certain video sources. bitchute.com

## Steps to reproduce:
1. Try to add any video from bitchute

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.6 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
I'm afraid that our library on Video App can't get video information from this source.

**Comment by prepperz** [comment]
Can you add it to the library?  With all the censorship that's going on on youtube, more alternatives are likely to emerge.

**Comment by spirogg** [comment]
Hi @prepperz how have you been. I hope all is well 
Spiro

**Comment by prepperz** [comment]
@spirogg

I'm doing well Just putting my head down and staying focused. Let's chat sometime about the possible future of things.

**Comment by harrison05** [comment]
> Can you add it to the library? With all the censorship that's going on on youtube, more alternatives are likely to emerge.

They have a lot of Video sites, our library can't cover all of them, just support popular sites. I hope you will understand. Btw, I have 2 suggestions for you:
- Add bitchute.com link on Post Status tab instead of Video tab.
- Request us a custom work, we will help you support bitchute.com on your site.

Regards.
