### ISSUE TITLE
Photo RESTful API: user_id parameter is ignored

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2748]
## What's happened?
When requesting photos owned by a specific member (using `user_id`  | Browse by owner id), RESTful API will return photos posted by other users anyway.

## Steps to reproduce:
1. Get everything necessary to make requests to RESTful API (create client, authorize user with `"grant_type": "password"`)
2. Post at least several photos by at least 2 different users not protected by any special privacy settings (using the website);
3. Make a request to [Photo API](https://docs.phpfox.com/display/FOX4DEVDOC/Photo+API) without `user_id` param to make sure that you're getting list of photos posted by 2 different members;
4. Make a request to [Photo API](https://docs.phpfox.com/display/FOX4DEVDOC/Photo+API) **with** `user_id` param equal to one of your user's IDs – you will receive not a filtered (expected) result, but a data from all users;

## What's expected?
It's expected to obtain data only for photos owned by a specific member when specifying `user_id` param.

## Browsers and Devices tested
Postman.

...

## Server information
CentOS Linux 7 (Core)
PHP Version: | 7.2.20
Apache Version | 2.4.39

...

## phpFox version
phpFox 4.7.7 (latest)
RESTful API | 4.2.3 (latest)

...

## Screenshots
![Screen Shot 2019-08-08 at 12 16 42](https://user-images.githubusercontent.com/5412712/62691144-ba39c980-b9d6-11e9-8474-62a9abf929a4.png)

**Comment by harrison05** [comment]
Which version of RestfulAPI you're using? Because we can't reproduce with the newest version. See my screenshots
![Screen Shot 2019-08-12 at 09 57 45](https://user-images.githubusercontent.com/41947198/62843930-d34cbe00-bce7-11e9-9a95-31dbc14b8948.png)
![Screen Shot 2019-08-12 at 09 57 57](https://user-images.githubusercontent.com/41947198/62843931-d34cbe00-bce7-11e9-9129-c8373b42e0a4.png)

**Comment by harrison05** [comment]
Which version of RestfulAPI you're using? Because we can't reproduce with the newest version. See my screenshots
![Screen Shot 2019-08-12 at 09 57 45](https://user-images.githubusercontent.com/41947198/62843960-1b6be080-bce8-11e9-9bfc-dcd9d2dc3b7c.png)
![Screen Shot 2019-08-12 at 09 57 57](https://user-images.githubusercontent.com/41947198/62843961-1b6be080-bce8-11e9-8f2a-be8d5fedee73.png)

**Comment by kirkkhua** [comment]
@harrison05 as mentioned in above post, `RESTful API | 4.2.3 (latest)`. Version of phpFox is `phpFox 4.7.7 (latest)`. 

Screenshots you presented contain only one element of each user. The result on my side includes correct elements with `user_id` corresponding to requested one, but also elements with random incorrect `user_id` I didn't request (as shown on above screenshots).

**Comment by harrison05** [comment]
> Screenshots you presented contain only one element of each user.

No, my screenshots show many photos of that **user_id**
![Screen Shot 2019-08-13 at 09 53 12](https://user-images.githubusercontent.com/41947198/62911994-9993ba00-bdb0-11e9-96e0-0a67ae5c6c9b.png)
Btw, our development team just check the source code of RESTFul Api and Photo Apps but don't find any mistake. If the issue still occurs on your site, you can submit a ticket.

Regards.

**Comment by kirkkhua** [comment]
just submitted a support ticket with FTP credentials

**Comment by harrison05** [comment]
Ok, our team will handle it. Please follow your ticket.

Regards.
