### ISSUE TITLE
Photo App: Please move file size and image dimensions to bottom. They are of no real importance at all to the user.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2756]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When you look at a photo, it shows the file size and dimensions before the album and category. This is no good at all. Who cares what the size and dimensions are... this is secondary technical  data! What is more important is the clickable album and category, which to make matter worse are hidden by default. Please switch them out.

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
Switch the pair out. Put In Album and Category (if any) first, then file size and dimensions.
Also, "in Album" should be "In Album". The word "in" should be capitalized to "In" and could not be located in phrases.

I get why it may be this way without even looking at the code. Photos may not be in albums or have categories, but that can be fixed with a few lines of code.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.7.7

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/63564631-db9cc880-c533-11e9-90ed-24163e811e7f.png)

![image](https://user-images.githubusercontent.com/48427415/63564671-05ee8600-c534-11e9-9736-b64fcc96bbd7.png)

**Comment by harrison05** [comment]
Oh, it sounds reasonable. I will discuss with my team about this.

Regards.

**Comment by afektmedia** [comment]
On this subject please also remove the default random number string displayed in mobile apps. Not only does this break the UX , when you click to view the image from mobile app you see this long horrible string of numbers. Since many people upload images directly from the main timeline, the image should not display this string. If they want to give it a name they can always edit it later. As of right now this makes all images in mobile app look horrible with these long number strings. Most people are familiar with Facebook and when you click  on a image from a FB timeline, you see the image only not the name displayed. 

![2E20F662-4663-482E-AF15-5086679E56D7](https://user-images.githubusercontent.com/5291057/65519759-5e9aa100-de9b-11e9-9cfd-6801de4ffeb3.jpeg)

**Comment by david-phpFox** [comment]
We have moved file size and image dimensions to bottom in Photos App 4.7.7.
