### ISSUE TITLE
flags don't show in popup for languages ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2776]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... hi I added 2 flags one for english and another for spanish for languages, after turn on feature the flags only show at the bottom next to languages English and Spanish language

I need to have them in popup next to english spanish why its not working, files are correct write permission.   

Steps to reproduce:
1. i added 2 images in languages, 1 for spanish 1 for english
2. turn on option to show images next to language
3. clear cache remove files not needed, clear all cache and rebuild core.

## What's expected?
...
 should show english and spanish flags in the popup language changer

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome firefox
...

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...
 
4.7.7 fresh install

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/65383021-53494900-dcd4-11e9-84e4-b501d8f02998.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/65383022-53494900-dcd4-11e9-9492-705d531aac5f.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/65383023-53494900-dcd4-11e9-82da-03ceeb75b363.PNG)

**Comment by spirogg** [comment]
PS. permissions are 777

**Comment by harrison05** [comment]
We will check this issue.

Thanks.

**Comment by harrison05** [comment]
Hi @spirogg ,

Our development team checked this issue and inform me that not a bug of phpFox, because we use **file_get_content** to verify flag image exists or not, please make sure your server enables this function. You can read more about this issue at:

https://stackoverflow.com/questions/14801955/php-file-get-contents-returning-false
https://stackoverflow.com/questions/2538723/ssl-received-a-record-that-exceeded-the-maximum-permissible-length-error-code

P/s: it's working well in our demo site.
![Screen Shot 2019-09-25 at 16 50 06](https://user-images.githubusercontent.com/41947198/65590376-e7593000-dfb4-11e9-98a5-2c8c5ddc7790.png)

**Comment by spirogg** [comment]
@harrison05

Yes you are correct in php I enabled allow_url_fopen

Cleared cache and rebuild core 
And now it's shows
Sorry and thank you for helping 🤗

Spiro
