### ISSUE TITLE
i think this is a double in phrases ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2801]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
 I did a search for register and it seems there is a double? not sure but can you check if this variable is double see photo
## Steps to reproduce:
1. go to phrases 
2. search "register"
3. now look at the screenshot I uploaded it seems these phrases are double unless I make mistake?

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Microsoft Edge on Windows 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 fresh install

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/66442693-62810400-ea01-11e9-9d0b-7c15c57cd21e.PNG)

**Comment by harrison05** [comment]
Hi @spirogg ,

Yes, I checked it. Those phrases were duplicated. 
But, don't remove phrase with the variable "**you_registered_an_account_on_site_title_before_being_able_to_use_your_account_you_need_to_verify_that_this_is_your_email_address_by_clicking_here_a_href_link_link_a**", because we're using it in our source code.
We will remove useless phrase "**you_registered_an_account_on_site_title_before**".

Regards.

**Comment by spirogg** [comment]
@harrison05 thank you  :)

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.9.
