### ISSUE TITLE
Nexmo SMS service

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2806]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Nexmo stopped to work in my site
...

## Steps to reproduce:
1. I start new registration ,users follow all steps but when they try to add phone number they got a red warning who say "contact administator" and they dont get the code.
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
IOS and Firefox

...

## phpFox version
(Example: phpFox 4.6.0)
4.7.8

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @Unite2Me 

I checked Nexmo SMS service and it's working well. If your site meet an issue with it. 
Make sure your Nexmo setting is correct (API Key, API Secret, Phone number) in AdminCP > Setting > Registration Settings.
If everything ok and the issue still occurs, please submit a Ticket in the Client Area. Our support team will help you figure it out.

Regards.

**Comment by Unite2Me** [comment]
For me dont work, i leave empty the phone number because i dont have (but months ago system work without phone number too)

maybe this happen because i have registration with invites setting ON?!

**Comment by harrison05** [comment]
> maybe this happen because i have registration with invites setting ON?!

No, this setting doesn't affect SMS verify. If you make sure your setting is fine but it still not working, please submit a ticket, our team will help you figure it out.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Nexmo SMS works perfect on my install although I did have to hack some code because no one puts a "1" in front U.S. telephone number these days as that was a 70's thing.

File:  PF.Base/include/library/phpfox/verify/driver/nexmo.class.php
public function sendSMS($to, $msg)
added after the first bracket:
$to = "1".$to;

this way they don't have to add the one each time when they enter their telephone number.

also,

File:  PF.Base/module/user/template/default/controller/sms/send.html.php
Change the title so the users would have a better understanding of what to enter.
<p class="help-block">Enter numbers only - no hypens or Parentheses ( example: 413788#### )</p>
