### ISSUE TITLE
user posted some songs in group email has no links and subject shows bold characters

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2811]
# Important

Please follow this template!

----------------------------------------

## What's happened?

- First the subject I received in email shows the `<B>Puerto-Rico</B>`  so it's not bold 

SUBJECT : 
Admin posted some songs on your group `<B>Puerto-Rico</B>`.

- Then I get this in message below with no link to the song I posted. 

...Hello admin,

Admin posted some songs on your group "Puerto Rico".
Follow the link below for more details:

- NO LINK WAS ATTACHED TO EMAIL HERE 
Kind Regards,
My website

## Steps to reproduce:
1. Create a group as admin, then Log in as another user and add some song 
2. As admin of the group you will receive the email 
3. The email subject shows the code <B> 
4. There is no link to the song 
## What's expected?
...
Should have link to song and not show the bold characters in subject of email 
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome 

## Server information
(Example: CentOS 7, php 7.1 apache)

... CentOS 7 php 7.3.10

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 fresh install 

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

Do you check the email content's phrase on your site? Because it had include link already

![Screen Shot 2019-10-15 at 10 50 49](https://user-images.githubusercontent.com/41947198/66799057-dd827700-ef39-11e9-9c2b-b3834bd116d3.png)

Btw, I found a problem with our phrase, link to group detail and link to item detail are duplicated. I think we should fix that.

Regards,
