### ISSUE TITLE
tooltip bug 

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2838]
I still see this bug in the latest phpfox.
 #2814

## phpFox version
PHPFOX 4.7.9

**Comment by harrison05** [comment]
Hi @Unite2Me 

Did you add custom CSS to your site?
Because I can't reproduce this issue on our site, then I have a quick check on your site, this is CSS code:
<img width="399" alt="Screen Shot 2019-11-29 at 10 08 15" src="https://user-images.githubusercontent.com/41947198/69841031-3f9bff00-1290-11ea-8589-464a872b8351.png">

And this is our CSS code:
![Screen Shot 2019-11-29 at 10 07 49](https://user-images.githubusercontent.com/41947198/69841047-55a9bf80-1290-11ea-8bfa-fe964310dc35.png)

You can see, your site has some new CSS and they override our CSS.

Regards.
