### ISSUE TITLE
Chat Plus - Datetime to European format

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2904]
Please add a function or use global setting to let change the visible Datetime Format in the Chat Plus App.

**Comment by harrison05** [comment]
Hi @Bjoern3003 

Which platform use are using? Desktop Website or Mobile App. Because on Web we apply the "Global Timestamp" setting for ChatPlus, on Mobile App, we're using DateTime from the device setting (timezone, time format).

Note: Please follow our template when you post a new topic (https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/ISSUE_TEMPLATE.md) it will help us to reproduce and detect issue quickly.

Regards

**Comment by Bjoern3003** [comment]
Hi, i mean desktop view. Which setting name are you using for this datetime?

**Comment by harrison05** [comment]
> Hi, i mean desktop view. Which setting name are you using for this datetime?

It applies the "Global Timestamp" setting
