### ISSUE TITLE
photos are pending after registration

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2969]
## What's happened?

wenn users are forced to upload a profile photo on registration and the setting to approve first is disabled all the photos are pending.

## What's expected?
photos should show up without approval.

## phpFox version
phpFox 4.8.2

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

> wenn users are forced to upload a profile photo on registration and the setting to approve first is disabled all the photos are pending.

Which setting you're talking about? "Force Users to Upload Profile Image" (user must upload avatar in singup form) or "Users are required to upload a profile image?" (user must upload avatar after signup success), please confirm. Because we got a bug with setting "Users are required to upload a profile image?" and it will be fixed in the next version (https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2947)

Regards.

**Comment by karlkunc** [comment]
I just fixed this issue. when the users upload the photo during registration they are in a guest membership status.
members>user group settings. select photos in the APP box and guest in the groups box. Then make sure they are allowed to upload and edit their photos.
