### ISSUE TITLE
video uploads on iPhone 11 Pro max IOS 14.4 do not show full width ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2999]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...when uploading a video from your iPhone and hold the phone sideways ( wide view to record as video, it still does not show wide.. ? 

but if I create a video on my iPhone in wide view and then later select and upload it shows in wide view on desktop sites.

in early versions of phpfox, I remember from Android the wide view recording and uploading worked well full width but now with iPhone full width is not possible? 

## Steps to reproduce:
1. go to videos and select upload video
2. hold phone side ways ( wide view ) and select video and start recording for a few 5 10 seconds.
3. then stop and upload that video and wait for ffmpeg to process then go to videos app to view on desktop,  open full screen does not show full screen?

- test another way -

1. record a video sideways  ( wide view on your iPhone.) first
2. now go to website from your iPhone and select upload video
3. select photos where your video is saved and select the video you created wide view
4. now upload that video and wait for ffmpeg to process 
5. now go to videos app on desktop and start video and select full screen view. 
6. you will see this video is full screen (wide view)  works as expected. 

## What's expected?
...
- should record in wide view when we turn the phone sideways and should be able to select full screen and watch the video in full screen

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
- recording in IOS 14.4 iPhone 11 Pro Max
- viewing in desktop safari chrome latest versions
...

## Server information
(Example: CentOS 7, php 7.1 apache)
CentOS 7 php 7.4 apache and Nginx 
...

## phpFox version
(Example: phpFox 4.6.0)
4.8.3 
...

## Screenshots
...SCREEN SHOT BELOW 

- 1ST Video is recorded while uploading.

- 2ND Video at the bottom of screen shot is recorded first then uploaded 

- both videos I was holding iPhone side ways before start recording - then started to record (wide view)

- 
<img width="1403" alt="Screen Shot 2021-03-07 at 10 23 43 PM" src="https://user-images.githubusercontent.com/17736688/110274726-1a1e9a80-7f95-11eb-885a-77f110e37a2f.png">

**Comment by spirogg** [comment]
PS I have set my iPhone to 4k 60 FPS in setting. but when click upload video and select video it does not give any options to set video to 4k 1080 720 etc. is there a possible way to add code in video app to be able to select what you want to record. 4k 1080 720 ? 

or 
- lets just get wideview full width recording to work please :)

thank you again hope you and your family are all Healthy my friend @harrison05 
Spiro

**Comment by harrison05** [comment]
Hi @spirogg 

We will check this issue.

Regards.

**Comment by harrison05** [comment]
Hi @spirogg 

This issue occurs because the resolution of video file when you record directly is not the same as the recorded file.

<img width="396" alt="Screen Shot 2021-03-24 at 16 13 25" src="https://user-images.githubusercontent.com/41947198/112284646-088b0180-8cbc-11eb-9646-c3fa20772845.png">

On iOS 14.4, if you use QuickTake (step 2 in your **Steps to Reproduce**) video always in 1080p - 30fps. It means video resolution is 480x360 (4:3) and after you uploaded and view it on feed, video width doesn't fully fill on feed container (16:9), so you will see black on sideways. This case also happens with some Android phones, it depends on video resolution. It isn't a bug from our Video app.
Btw, we will improve in the next version and don't set a ratio 16:9 to all videos uploaded on newfeed to make sure almost them will show full width.

Regards.

**Comment by harrison05** [comment]
We improved the layout of video on feeds in version 4.7.9

Regards.
