### ISSUE TITLE
cron.log and mail.log - how long will the fill up? we need automate to clear or rotate 2 weeks or so?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#3000]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... hi I chalk the cron.log, I have every 5mins my cron running, and this is running now for 1 month almost 10,000 lines so far.

do we clear the cron.log file with anther cron job? or do we have to manually clear this log file?

would be nice if you set to **clear cron.log and mail.log after 30days** 

- or **rotating 2 weeks** ? 
- so every 2 weeks the older ones get deleted and the newer ones stay..

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
... some sort of automation to clear the cron.log and mail.log

ALSO set this to 0644 

chmod 0777 is not good.
chmod 0644 is good and still writes.. 

for safer solution!

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...centOS 7 php7.4 apache and Nginx 

## phpFox version
(Example: phpFox 4.6.0)

... 4.8.3

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

We understood this case, we will check and find a solution. 
Maybe, an improvement on Log Handling to allow each log driver clear old logs.

Regards.

**Comment by harrison05** [comment]
Hi @spirogg 

We just only support manual delete a Log Channel when Admin access to AdminCP > Settings > Log Handling and view detail a specific log channel. You can see my screenshot.

![Screen Shot 2021-04-12 at 14 51 45](https://user-images.githubusercontent.com/41947198/114359908-a593d880-9b9e-11eb-911d-0e8ece30c2b2.png)

We don't support cron job to automatically delete logs because we want Admin to know which logs are logged on their site and they don't be miss.

Regards.
