### ISSUE TITLE
after upgrade 4.8.4 my template is not rebuilt with Mterial template so @mary does not work

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#3008]
# Important

Please follow this template!
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2966#issuecomment-820960256
#2966 
----------------------------------------

## What's happened?
... after update to 4.8.4 my template i created will not follow Material tempate so @mary does not work

@harrison05 the issue is the template. i created my own template back in 4.8.0 - (example create new template from material, named it mywebsite)

I added my logo and favicon
saved mywebsite as the default template

now I do the upgrade, to 4.8.4

now I remove files no longer needed, find missing settings, then language - find missing phrases, then rebuild core theme, then clear cache...

now i try to type @harrison05 in feed and it does not work, so I go to templates and change to original Material template and set as default.  clear cache and now it works.

- so the issue is the template before the upgrade, it does not change or rebuild to the same as material template

- **only the original Material template as default works when @harrison05 in feed.**

- **this has to be a bug**

## Steps to reproduce:
1. 4.8.3 and before create a new template from Material ( name it phpfox2 ( or whatever you name it)
2. now upgrade to 4.8.4 and after finish ( try in feed to add @whateveruser it will not work will show code
2. now go to templates and change to default Material template ( original) save as default template clear cache 
3. now go to feed and try again @whateveruser now it will work. 

## What's expected?
... should copy Material to your own default template so all changes will follow

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome edge firefox

## Server information
(Example: CentOS 7, php 7.1 apache)

... centos 7 php 7.4

## phpFox version
(Example: phpFox 4.6.0)

...
4.8.4

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg

Because the new version of Material has some changes in source code to make sure it compatible with phpFox 4.8.4, but your template cloned before so it doesn't compatible with it. 

To make new mention work on your template you can clone a new template from Material 4.8.2 and set it as default - but you need to store your current template configures and update to the new.

OR you can hotfix by override 2 files from Material into your template:
- PF.Site/flavors/material/html/feed.block.form.html.php -> PF.Site/flavors/your_template/html/feed.block.form.html.php
- PF.Site/flavors/material/html/feed.block.edit-user-status.html.php -> PF.Site/flavors/your_template/html/feed.block.edit-user-status.html.php

Btw, we will add a new feature to support Admin merge source codes from Material into their own template to make sure it doesn't outdate with phpFox from AdminCP.

Regards.

**Comment by harrison05** [comment]
The new feature that supports Admin merge source codes from Material into their own template is now available in phpFox v4.8.6

Regards.

**Comment by Mary** [comment]
@harrison05 @spirogg please remove my username so that I don't get any notifications about your project! :) good luck!
