### ISSUE TITLE
Newsletter cron error

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3015]
##What's happened?
I added a newsletter and after saving the progress shows 0/0 and status "sending". No mails are sent at all.

Cron is set up and notifications and testmails are sending. the cron log shows following error: cron.log.DEBUG: job not found {"job":"core_newsletter_send_email_users"}

##Steps to reproduce:
Add new Newsletter with text and all usergroups
Start sending

##What's expected?
The table should show the amount of newsletters and send them to the users

##Server information
Linux Debian 10

##phpFox version
phpFox 4.8.4
Latest Newsletter app

**Comment by harrison05** [comment]
Related to #3012

**Comment by harrison05** [comment]
I guess it has an issue with Data Cache on your site so it can't detect cronjob handling of Newsletter App.

**Comment by kibcode** [comment]
the sites using filesystem cache. i have also deacitvated opcache to see if there are issues with that but it does not work. any ideas what else i can check?

**Comment by harrison05** [comment]
As I know, log "job not found" only shows if the system executes a job without a handler. If you're a developer, you can debug in function \Core\Queue\Manager::loadHandlers and figure out why plugin "job_queue_init" of Newsletter doesn't run? (We cache all hooks before running it, so without cache > hooks won't run).

P/s: I recommend you submit a ticket, our support team with help you with this bug.

Regards.

**Comment by Elshara** [comment]
I had the same issue literally for years.
To solve it I had to install SocialEngine and import my entire
community to use their CURL implementation to get around it because
the newsletters just couldn't send otherwise. Not on their own, or
even with me manually processing the pages in a browser.
Cron in PHPFox has always ran fine like any other command I ran
through the job queue. The implementation of the Newsletter app has
always never worked even after multiple fresh installs with just me as
a member. It's actually one of the primary reasons why I had to revert
to SocialEngine because of a working newsletter system and mail queue
in that platform.
