### ISSUE TITLE
Friends only community

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3032]
## What's happened?
My users are very confused when I activate friends only community. Since there is only the selection "friends of friends" in their privacy setting it is not possible for new users to send any friend requests. how can new users add friends without already having a friend? seems like a bug to me because it makes no sense.

## Steps to reproduce:
1. Register a new user
2. Browse users to find people you know
3. Try to send friend request

## What's expected?
In a friends only community users should be able to find friends. There must be a privacy setting "community" for friends only sites.

## phpFox version
phpFox 4.8.8

**Comment by harrison05** [comment]
Hi @Kibcode 

We will check and find a solution to this issue. 
Allow "Community" option on setting "Who can send me a friend request?" might be a good solution, thanks for your suggestion.

Regards.

**Comment by kibcode** [comment]
thanks @harrison05 can you provide a hotfix for that?

**Comment by harrison05** [comment]
This issue must be fixed in many places in source codes, so I can't write it down here. You can submit a ticket in the client area, we can apply a hotfix for your site. 
P/s: another tip, you can set an admin for setting "On Signup New Friend", new users will have a mutual friend and they can send friend requests for each other

Regards.

**Comment by harrison05** [comment]
This issue was fixed on phpFox v4.8.9

Regards.
